### PR TITLE
TST: Use a slightly more realistic test case

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix the failing test case in CI.

### CODE REVIEW

**Comment by duytnguyendtn** [comment]
Was there an issue with the test cube I made? :/

**Comment by pllim** [comment]
Not sure, never did find the exact cause. `arange` with handwritten WCS is probably not recommended anyway. We have premade image cube from `conftest.py`.

**Comment by pllim** [comment]
CI passed. You can ignore the change log check here.

**Comment by duytnguyendtn** [comment]
Thank you so much @pllim !! 🙇

**Pull request merged**
